# Generated by Django 5.2.12 on 2026-04-06 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsapp', '0004_resource_topic_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='topic_uuid',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
