# Generated by Django 5.2.12 on 2026-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsapp', '0005_remove_resource_topic_uuid_topic_topic_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/pdf/'),
        ),
    ]
