# Generated by Django 5.2.12 on 2026-04-09 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsapp', '0007_question_choice_quiz_question_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Sekundlarda (har bir savol)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='session_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='session_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='session_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='max_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='earned_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#1a56db', max_length=7),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', "Bitta to'g'ri javob (Radio)"), ('multiple', "Bir nechta to'g'ri javob (Checkbox)"), ('true_false', "To'g'ri / Noto'g'ri")], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=15, help_text='Minutlarda (quiz uchun umumiy)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, to='spsapp.choice'),
        ),
    ]
